### ISSUE TITLE
Security shouldn't be optional

### ISSUE THREAD

**Issue by ghost** [gius-italy/polito_dl#4]
for security reasons, the `--password` option should not exist.
Take a look at the man page of `ssh`... do you see any `--password` option out there?
No? Well... OpenSSH was made by OpenBSD, and these guys are pretty known to be
very badass cybersecurity engineers, so... if they didn't add a `--password` option in `openssh`,
there must be at least one good reason.

**Comment by lvps** [comment]
The good reason is: your plaintext password will end up in bash history or in a log file.
