### ISSUE TITLE
docopt ModuleNotFoundError

### ISSUE THREAD

**Issue by e-caste** [gius-italy/polito_dl#6]
Thanks for this script!
I've installed the requirements, but when running the script it throws an exception and exits:
`Traceback (most recent call last):
  File "polito_dl.py", line 32, in <module>
    from docopt import docopt
ModuleNotFoundError: No module named 'docopt'`
I've tried looking it up online but I haven't found a possible cause, since I'm not using conda but pip3 as a package manager and I'm on macOS, while the issues people are having are mostly on Windows.
Do you have any idea how to solve it?
docopt is version 0.6.2, do you mind commenting with your version?

**Comment by glumia** [comment]
Hi! I'm also using pip3 but on Ubuntu and my version is also 0.6.2.
I know it could sound like an obvious question, but are you sure you're running the script with python3 and not python2? 
Could you please post the output of "pip3 list" ?

**Comment by e-caste** [comment]
Yes, I'm sure I'm using Python 3, 3.7.0 to be precise. 
docopt is in my pip3 list output

**Comment by glumia** [comment]
Maybe it's a problem with the PYTHONPATH environment variable. Check if the docopt installation path is present.  (For example on my system it's "~/.local/lib/python3.6/site-packages" )

**Comment by e-caste** [comment]
Okay, I fixed it. On my version of pip3 (19.0.3) just using `sudo pip3 install <package>` won't work anymore. I just needed to `sudo pip3 uninstall docopt` and reinstall it with `pip3 install --user docopt`. I agree it's an issue of the PYTHONPATH variable. 
Another possible fix may be using `sudo -H pip3 install docopt`.
Closing this issue now, thanks for the replies!
